version: 2.1
orbs:
  docker: circleci/docker@0.1.0
workflows:
  build-and-publish:
    jobs:
      - docker/publish:
          name: build-and-publish-node-image-dockerhub
          context: docker-hub-publishing
          filters:
            branches:
              only: master
          image: hellomd/ci-node
          dockerfile: node.dockerfile
          after_build:
            - run:
                name: Tag as latest
                command: |
                  docker tag \
                    docker.io/hellomd/ci-node:$CIRCLE_SHA1 \
                    docker.io/hellomd/ci-node:latest
            - run: docker push docker.io/hellomd/ci-node:latest
